import type { Metadata } from "next";
import Link from "next/link";
import "../home.css";
import "../mobile.css";
import "../legal/legal.css";
import { LegalPage } from "@/components/legal/LegalPage";

export const metadata: Metadata = {
  title: "Terms of Service",
  description:
    "The terms you agree to when you use the OneStop AI website and Jarvis. Education, information and automation support — never financial advice.",
};

/** TODO(counsel): the limitation of liability and governing law clauses need a
 *  lawyer before we take money. TODO(launch): registered entity name, address
 *  and jurisdiction below are placeholders. */
export default function TermsPage() {
  return (
    <LegalPage
      eyebrow="Legal"
      title="Terms of Service"
      intro="The agreement between you and OneStop AI when you use this site or Jarvis. The short version: Jarvis informs you, it never advises you, and the decisions stay yours."
      updated="10 September 2026"
    >
      <section>
        <div className="draft">
          <p>
            <b>Draft.</b> These terms are published for the invite-only beta and are under
            review by counsel. They will be updated before Jarvis is generally available.
          </p>
        </div>
      </section>

      <section>
        <h2>Who you are contracting with</h2>
        <p>
          These Terms are between you and <b>[REGISTERED ENTITY NAME]</b>, a company
          registered at [REGISTERED ADDRESS] and trading as OneStop AI
          (&ldquo;OneStop&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;). They govern your use
          of this website and the Jarvis application (together, the
          &ldquo;Service&rdquo;).
        </p>
        <p>
          By using the Service you accept these Terms. If you do not accept them, do not use
          the Service.
        </p>
      </section>

      <section>
        <h2>Not financial advice</h2>
        <div className="note">
          <p>
            OneStop AI provides education, information, and automation support &mdash; never
            financial advice. Jarvis, our first product, does not sell products or recommend
            securities.
          </p>
        </div>
        <p>
          Nothing the Service produces is investment, tax, legal or accounting advice, and
          nothing in it is an offer, solicitation or recommendation to buy or sell any
          security or financial product. We are not your broker, investment adviser,
          research analyst or fiduciary, and using the Service does not create any such
          relationship.
        </p>
        <p>
          Jarvis reflects your position back to you and helps you understand it. Every
          decision you make with it remains yours. <b>Investing carries risk, including the
          loss of principal. Past performance does not indicate future results.</b> Consult a
          licensed professional before acting on anything you read here.
        </p>
        <p>
          Jarvis is generated by AI models and can be wrong, incomplete or out of date. Do
          not rely on it as your only source, and verify anything that matters against your
          own records and your broker&rsquo;s statements.
        </p>
      </section>

      <section>
        <h2>Eligibility and your account</h2>
        <ul>
          <li>You must be at least 18 and able to enter a binding contract.</li>
          <li>You must give accurate information and keep it current.</li>
          <li>You are responsible for your credentials and for everything done under your account.</li>
          <li>Tell us promptly at <a href="mailto:support@onestop.ai">support@onestop.ai</a> if you suspect unauthorised access.</li>
        </ul>
        <p>
          Jarvis is currently in invite-only beta. Beta features may change, break or be
          withdrawn without notice, and may not be as reliable as a generally available
          product.
        </p>
      </section>

      <section>
        <h2>Acceptable use</h2>
        <p>You agree not to:</p>
        <ul>
          <li>Use the Service unlawfully, or to break any financial or securities regulation.</li>
          <li>Present Jarvis&rsquo;s output to anyone else as licensed financial advice.</li>
          <li>Reverse engineer, scrape, or attempt to extract the underlying models or prompts.</li>
          <li>Probe, disrupt or overload the Service or its infrastructure.</li>
          <li>Upload malware, or data you have no right to share.</li>
          <li>Impersonate anyone, or access another person&rsquo;s account.</li>
          <li>Resell or commercially redistribute the Service without our written permission.</li>
        </ul>
      </section>

      <section>
        <h2>Your data and your content</h2>
        <p>
          What we collect and how we handle it is set out in our{" "}
          <Link href="/privacy">Privacy Policy</Link>. You keep ownership of everything you put
          into the Service. You grant us only the licence needed to operate the Service for
          you &mdash; to store, process and display your content back to you. We do not use
          your content to train AI models.
        </p>
      </section>

      <section>
        <h2>Connected accounts</h2>
        <p>
          If you link a broker or bank, you confirm you are authorised to do so. We request
          read-only access: we do not place trades or move money. Your relationship with that
          institution is governed by its own terms, and we are not responsible for its
          accuracy, availability, or acts.
        </p>
      </section>

      <section>
        <h2>Our intellectual property</h2>
        <p>
          The Service, its software, design, and the OneStop and Jarvis marks belong to us
          and our licensors. We grant you a limited, personal, non-exclusive, non-transferable,
          revocable licence to use the Service under these Terms. Nothing else is granted.
        </p>
      </section>

      <section>
        <h2>Fees</h2>
        <p>
          Jarvis is free during the invite-only beta. If we introduce fees we will tell you
          before they apply to you, and paid plans will be governed by the pricing terms
          presented at the time you subscribe.
        </p>
      </section>

      <section>
        <h2>Suspension and termination</h2>
        <p>
          You may stop using the Service and close your account at any time. We may suspend
          or terminate your access if you breach these Terms, if we are required to by law,
          or if we discontinue the Service. We will give reasonable notice where we can. On
          termination your licence ends; the sections that by their nature should survive
          &mdash; ownership, disclaimers, liability, governing law &mdash; do.
        </p>
      </section>

      <section>
        <h2>Disclaimers</h2>
        <p>
          The Service is provided <b>&ldquo;as is&rdquo; and &ldquo;as available&rdquo;</b>,
          without warranties of any kind, express or implied, including merchantability,
          fitness for a particular purpose, non-infringement, and any warranty as to the
          accuracy, completeness or timeliness of information. We do not warrant that the
          Service will be uninterrupted, secure or error-free.
        </p>
      </section>

      <section>
        <h2>Limitation of liability</h2>
        <p>
          To the fullest extent the law permits, OneStop and its officers, employees and
          suppliers are not liable for any indirect, incidental, special, consequential,
          punitive or exemplary damages, or for lost profits, lost data, lost opportunity, or{" "}
          <b>any investment or trading loss</b> arising from your use of the Service &mdash;
          whether or not we were told such damages were possible.
        </p>
        <p>
          Our total aggregate liability for all claims relating to the Service is limited to
          the greater of the amount you paid us in the twelve months before the claim, or
          [AMOUNT]. Some jurisdictions do not allow these exclusions, so parts of this
          section may not apply to you.
        </p>
      </section>

      <section>
        <h2>Indemnity</h2>
        <p>
          You agree to indemnify OneStop against claims, losses and reasonable legal costs
          arising from your use of the Service, your content, or your breach of these Terms
          or of any law.
        </p>
      </section>

      <section>
        <h2>Governing law and disputes</h2>
        <p>
          These Terms are governed by the laws of <b>[JURISDICTION]</b>, without regard to
          conflict of law rules. The courts of <b>[CITY, JURISDICTION]</b> have exclusive
          jurisdiction over any dispute, and you and we submit to that jurisdiction. Before
          filing, please contact us at{" "}
          <a href="mailto:legal@onestop.ai">legal@onestop.ai</a> so we can try to resolve it.
        </p>
      </section>

      <section>
        <h2>Changes</h2>
        <p>
          We may update these Terms. We will update the date above and, for material changes,
          tell you by email or in the product before they take effect. Continuing to use the
          Service after that means you accept the new Terms.
        </p>
      </section>

      <section>
        <h2>Contact</h2>
        <p>
          [REGISTERED ENTITY NAME] &middot; [REGISTERED ADDRESS]<br />
          <a href="mailto:legal@onestop.ai">legal@onestop.ai</a>
        </p>
      </section>
    </LegalPage>
  );
}
